### ISSUE TITLE
Milestone 02 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/PySyntext#40]
Hello,

- I see that you are on track and did everything required in Milestone 02.
- The package setup  run without any problems
- You have efficiently used github workflow efficiently including branching, issue tracker,...
- By running the examples on `text_grams` function, it always throws an error. That is affecting the tests too. Please check..

Thanks!

**Comment by hsmohammed** [comment]
Hi,
I rechecked the error I got and to solve the problem I had to download 'stopwords' from the `nltk` module.
I suggest you add a note in the pachage readme file containing the following code:
```
import nltk
nltk.download('stopwords')
```

Thanks!

**Comment by HarjyotKaur** [comment]
Thanks for the review Hossam, the issue has been addressed.
