### ISSUE TITLE
Feedback on proposal

### ISSUE THREAD

**Issue by VaradaKolhatkar** [UBC-MDS/PySyntext#9]
Interesting idea! I already spoke with you yesterday but here are a few more comments on the proposal. 

- You are already doing this but make it explicit that will be working with a piece of text and **not** a text column. 
- A picky comment: [Python function and variable naming convention](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) suggests using lowercase with words separated by underscores. For example, I would rename `TextGrams` with something like `show_popular_terms`. 
- You might want to consider [readability](https://en.wikipedia.org/wiki/SMOG) in the `TextQuality` function. 
- You are supposed to write only three functions. I would either get rid of function 4 or kind of merge it with function 3. 

Here are some tools which do similar things.  
http://guides.library.illinois.edu/c.php?g=405110&p=2803418

Looking forward to seeing how this project develops!

**Comment by HarjyotKaur** [comment]
Hi Varada,

Thanks for your feedback. 

- We have made explicit that we will be treating a text i.e  a string and not a column of strings.
- Converted entire package framework to lowercase
- Changed text_quality, it now returns spell_error and toxicity. We were wondering if we should return only the proportion of spelling errors and toxicity or the count of words also?
- We dropped the fourth function (POS Tagging).
